---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '2048'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                qkXnDwxXUpKD:
                    host: '8080'
                    guest: '80'
                eZJPF7m7IJ2w:
                    host: '4043'
                    guest: '443'
                chLUym9QR5z0:
                    host: '3306'
                    guest: '3306'
                Eo0GbbuQEYog:
                    host: '15432'
                    guest: '5432'
        post_up_message: 'Congratulations! You should setup your local hosts file with 192.168.56.101 drupal8.mysql.dev drupal8.pgsql.dev drupal8.sqlite.dev, and then you can browse to http://drupal8.mysql.dev to get started!'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            r8LFbJfVnY2g:
                owner: ''
                group: ''
                source: www
                target: /var/www
                sync_type: rsync
                rsync:
                    args:
                        - '-rtlDPvcz'
                        - '--delete'
                    exclude:
                        - .vagrant/
                        - .git/
                        - 'sites/*/settings.php'
                        - 'sites/*/services.yml'
                        - 'sites/*/files/'
                        - '.*.swp'
                        - node_modules
                        - .sass-cache/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - samba
        - vim
        - postgresql-contrib
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        hcfedouptcif:
            servername: drupal8.mysql.dev
            serveraliases:
                - www.drupal8.mysql.dev
            docroot: /var/www/drupal8.dev
            port: '80'
            custom_fragment: ''
            directories:
                6lkgsxm4uhsr:
                    provider: directory
                    path: /var/www/drupal8.dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        0nrosax43wdq:
            servername: drupal8.pgsql.dev
            serveraliases:
                - www.drupal8.pgsql.dev
            docroot: /var/www/drupal8.dev
            port: '80'
            custom_fragment: ''
            directories:
                u9l1rrwc6jej:
                    provider: directory
                    path: /var/www/drupal8.dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        dd0c2npj1yhu:
            servername: drupal8.sqlite.dev
            serveraliases:
                - www.drupal8.sqlite.dev
            docroot: /var/www/drupal8.dev
            port: '80'
            custom_fragment: ''
            directories:
                9tzhisfjszyk:
                    provider: directory
                    path: /var/www/drupal8.dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        yofbeppjgdh7:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - curl
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        memory_limit: 256M
        session.save_path: /var/lib/php/session
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '1'
    version: 7.0.0-alpha3
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        Hz0IgO90ZuR4:
            name: drupal8
            password: drupal8
    databases:
        G6UE9ClMBE3K:
            name: drupal8
            sql: ''
    grants: {  }
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.1'
        server:
            postgres_password: drupal8
    databases:
        qJINz7iiWWR3:
            dbname: drupal8
            owner: drupal8
    users:
        JqtZfW7u0qAh:
            username: drupal8
            password: drupal8
    grants: {  }
    adminer: 0
sqlite:
    install: '1'
    adminer: 0
    databases:
        VWMNThfRMEnq:
            name: drupal8
            owner: vagrant
            group: vagrant
            mode: '775'
            sql_file: ''
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

